blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://opus-ui.com/discord
    about: Ask questions and discuss with other Opus UI Language Server VSCode Client users in real time.
